version: '3.9'

services:

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
    - "${PG_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always

    ports:
      - "${ADMINER_PORT}:8080"

    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PG_HOST: postgres_db
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
    depends_on:
      - db


  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_db:5432/${PG_DB}
      KC_DB_USERNAME: ${PG_USER}
      KC_DB_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  postgres_data: