events {}

http {

  upstream api_cluster {
    server api:3001;
  }

  upstream search_cluster {
    server search-service:4000;
  }

  upstream spark_cluster {
    server spark-service:8000;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://api_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /search/ {
      proxy_pass http://search_cluster/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    #  Spark / FastAPI analytics
    location /analytics/ {
      proxy_pass http://spark_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

  }
}