events {}

http {
  server {
    listen 80;

    # API
    location /api/ {
      proxy_pass http://api:3001;
    }

    # SEARCH
    location /search/ {
      proxy_pass http://search-service:4000;
    }
  }
}